# Activate with: --spring.profiles.active=postgres
conductor.db.type=postgres
conductor.queue.type=postgres

spring.datasource.url=jdbc:postgresql://localhost:5432/coss
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.hikari.maximum-pool-size=8
spring.datasource.hikari.auto-commit=false

conductor.indexing.enabled=true
conductor.indexing.type=postgres
conductor.external-payload-storage.type=postgres
conductor.workflow-execution-lock.type=postgres
