"""Example groups and HITL stdin mappings."""

GROUPS: dict[str, list[str]] = {
    "HITL_EXAMPLES": [
        "02_tools",
        "09_human_in_the_loop",
        "09b_hitl_with_feedback",
        "09c_hitl_streaming",
    ],
    "SLOW_EXAMPLES": [
        "08_router_agent",
        "13_hierarchical_agents",
        "23_token_tracking",
        "31_tool_guardrails",
    ],
    "KNOWN_FAILURES": [
        "14_existing_workers",
        "21_regex_guardrails",
        "22_llm_guardrails",
        "33_external_workers",
        "34_prompt_templates",
        "39c_serverless_code_execution",
    ],
    "PASSING_EXAMPLES": [
        "01_basic_agent",
        "02a_simple_tools",
        "02b_multi_step_tools",
        "03_structured_output",
        "05_handoffs",
        "06_sequential_pipeline",
        "07_parallel_agents",
        "10_guardrails",
        "11_streaming",
        "12_long_running",
        "15_agent_discussion",
        "16_random_strategy",
        "17_swarm_orchestration",
        "18_manual_selection",
        "19_composable_termination",
        "20_constrained_transitions",
        "29_agent_introductions",
        "30_multimodal_agent",
        "32_human_guardrail",
        "33_single_turn_tool",
        "35_standalone_guardrails",
        "36_simple_agent_guardrails",
        "37_fix_guardrail",
        "38_tech_trends",
        "39_local_code_execution",
        "39a_docker_code_execution",
        "39b_jupyter_code_execution",
        "40_media_generation_agent",
        "41_sequential_pipeline_tools",
        "42_security_testing",
        "43_data_security_pipeline",
        "44_safety_guardrails",
        "45_agent_tool",
        "46_transfer_control",
        "47_callbacks",
        "48_planner",
        "49_include_contents",
        "50_thinking_config",
        "51_shared_state",
        "52_nested_strategies",
    ],
    "OPENAI_EXAMPLES": [
        "openai/01_basic_agent",
        "openai/02_function_tools",
        "openai/03_structured_output",
        "openai/04_handoffs",
        "openai/05_guardrails",
        "openai/06_model_settings",
        "openai/07_streaming",
        "openai/08_agent_as_tool",
        "openai/09_dynamic_instructions",
        "openai/10_multi_model",
    ],
    "ADK_EXAMPLES": [
        "adk/01_basic_agent",
        "adk/02_function_tools",
        "adk/03_structured_output",
        "adk/04_sub_agents",
        "adk/05_generation_config",
        "adk/06_streaming",
        "adk/07_output_key_state",
        "adk/08_instruction_templating",
        "adk/09_multi_tool_agent",
        "adk/10_hierarchical_agents",
        "adk/11_sequential_agent",
        "adk/12_parallel_agent",
        "adk/13_loop_agent",
        "adk/14_callbacks",
        "adk/15_global_instruction",
        "adk/16_customer_service",
        "adk/17_financial_advisor",
        "adk/18_order_processing",
        "adk/19_supply_chain",
        "adk/20_blog_writer",
        "adk/21_agent_tool",
        "adk/22_transfer_control",
        "adk/23_callbacks",
        "adk/24_planner",
        "adk/25_camel_security",
        "adk/26_safety_guardrails",
        "adk/27_security_agent",
        "adk/28_movie_pipeline",
        "adk/29_include_contents",
        "adk/30_thinking_config",
        "adk/31_shared_state",
        "adk/32_nested_strategies",
    ],
    "LANGGRAPH_EXAMPLES": [
        "langgraph/01_hello_world",
        "langgraph/02_react_with_tools",
        "langgraph/03_memory",
        "langgraph/04_simple_stategraph",
        "langgraph/05_tool_node",
        "langgraph/06_conditional_routing",
        "langgraph/07_system_prompt",
        "langgraph/08_structured_output",
        "langgraph/09_math_agent",
        "langgraph/10_research_agent",
        "langgraph/11_customer_support",
        "langgraph/12_code_agent",
        "langgraph/13_multi_turn",
        "langgraph/14_qa_agent",
        "langgraph/15_data_pipeline",
        "langgraph/16_parallel_branches",
        "langgraph/17_error_recovery",
        "langgraph/18_tools_condition",
        "langgraph/19_document_analysis",
        "langgraph/20_planner_agent",
        "langgraph/21_subgraph",
        "langgraph/23_retry_on_error",
        "langgraph/24_map_reduce",
        "langgraph/25_supervisor",
        "langgraph/26_agent_handoff",
        "langgraph/27_persistent_memory",
        "langgraph/29_tool_categories",
        "langgraph/30_code_interpreter",
        "langgraph/31_classify_and_route",
        "langgraph/32_reflection_agent",
        "langgraph/33_output_validator",
        "langgraph/34_rag_pipeline",
        "langgraph/35_conversation_manager",
        "langgraph/36_debate_agents",
        "langgraph/37_document_grader",
        "langgraph/38_state_machine",
        "langgraph/39_tool_call_chain",
        "langgraph/40_agent_as_tool",
        "langgraph/41_react_agent_basic",
        "langgraph/42_react_agent_system_prompt",
        "langgraph/44_context_condensation",
    ],
    "LANGGRAPH_HITL": [
        "langgraph/22_human_in_the_loop",
    ],
    "LANGGRAPH_NATIVE": [
        "langgraph/28_streaming_tokens",
    ],
    "LANGGRAPH_MULTI_MODEL": [
        "langgraph/43_react_agent_multi_model",
    ],
    "LANGCHAIN_EXAMPLES": [
        "langchain/01_hello_world",
        "langchain/02_react_with_tools",
        "langchain/03_custom_tools",
        "langchain/04_structured_output",
        "langchain/05_prompt_templates",
        "langchain/06_chat_history",
        "langchain/07_memory_agent",
        "langchain/08_multi_tool_agent",
        "langchain/09_math_calculator",
        "langchain/10_web_search_agent",
        "langchain/11_code_review_agent",
        "langchain/12_document_summarizer",
        "langchain/13_customer_service_agent",
        "langchain/14_research_assistant",
        "langchain/15_data_analyst",
        "langchain/16_content_writer",
        "langchain/17_sql_agent",
        "langchain/18_email_drafter",
        "langchain/19_fact_checker",
        "langchain/20_translation_agent",
        "langchain/21_sentiment_analysis",
        "langchain/22_classification_agent",
        "langchain/23_recommendation_agent",
        "langchain/24_output_parsers",
        "langchain/25_advanced_orchestration",
    ],
    "SMOKE_TEST": [
        "01_basic_agent",
        "03_structured_output",
        "openai/01_basic_agent",
        "openai/03_structured_output",
        "openai/04_handoffs",
        "adk/01_basic_agent",
        "adk/03_structured_output",
    ],
}

HITL_STDIN: dict[str, str] = {
    "02_tools": "y",
    "09_human_in_the_loop": "y",
    "09b_hitl_with_feedback": "a",
    "09c_hitl_streaming": "y",
    "langgraph/22_human_in_the_loop": "approve",
}
